/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cdshop;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quy
 */
public class hoadon extends javax.swing.JFrame {
        public void setTextField1Value(String value) {
        jTextField1.setText(value);
    }
        LocalDateTime currentTime = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String formattedTime = currentTime.format(formatter);
        
        LocalDateTime sevenday = currentTime.plusDays(7);
        String sevendayFormat = sevenday.format(formatter);
        
        LocalDateTime fourteenday = currentTime.plusDays(14);
        String fourteendayFormat = fourteenday.format(formatter);
        
        LocalDateTime thirdtyday = currentTime.plusDays(21);
        String thirdtydayFormat = thirdtyday.format(formatter);
//        String p = price.getText();
        


    /**
     * Creates new form hoadon
     */
    public hoadon() throws SQLException {
        initComponents();
        nhanvien.setText(SharedData.adminName);
        txtngaymuon1.setText(formattedTime);
        txtngaytra1.removeAllItems();
        txtngaytra1.addItem(sevendayFormat);
        txtngaytra1.addItem(fourteendayFormat);
        txtngaytra1.addItem(thirdtydayFormat);
    }

    private int getPriceBorrowDate(){
        int rowCount = bang1.getRowCount();
        if(rowCount > 0 ){
            int totalPrice = 0;
            for (int i = 0; i < rowCount; i++) {
                int price = Integer.parseInt(bang1.getValueAt(i, 4).toString()) * Integer.parseInt(bang1.getValueAt(i, 5).toString());
                totalPrice += price;
            }

            int ngayTra = txtngaytra1.getSelectedIndex();
            if(ngayTra==0 ){
                return totalPrice;
            }else if(ngayTra == 1){
                return ((totalPrice*25)/100)+totalPrice; 
            }else if(ngayTra ==2){
                return ((totalPrice*50)/100)+totalPrice;
            }
        }
        
        return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namevideo = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        idvideo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tonkho = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        namekh = new javax.swing.JTextField();
        txtthethanhvien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtngaymuon1 = new javax.swing.JTextField();
        txtngaytra1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tienkhachdua = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tienthua = new javax.swing.JTextField();
        tongtien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bang1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nhanvien = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        trangthai = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(253, 255, 232));
        jPanel1.setForeground(new java.awt.Color(252, 255, 222));

        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Mã video");

        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("Tên");

        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setText("Giá");

        namevideo.setEditable(false);
        namevideo.setBackground(new java.awt.Color(204, 204, 204));

        price.setEditable(false);
        price.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setText("Số lượng");

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setText("Thêm sản phẩm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        xoa.setBackground(new java.awt.Color(51, 204, 255));
        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        idvideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idvideoActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(51, 0, 0));
        jLabel15.setText("Thể loại");

        category.setEditable(false);
        category.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setText("Số lượng tồn kho:");

        tonkho.setEditable(false);
        tonkho.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idvideo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(tonkho, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namevideo, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(category))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(xoa))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idvideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tonkho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(namevideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jButton2))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("MƯỢN VIDEO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel14.setText("Nhân viên:");

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel11.setForeground(new java.awt.Color(0, 102, 0));
        jLabel11.setText("Thẻ thành viên:");

        namekh.setEditable(false);
        namekh.setBackground(new java.awt.Color(204, 204, 204));
        namekh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namekhActionPerformed(evt);
            }
        });

        txtthethanhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtthethanhvienActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Tên khách hàng:");

        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Thời gian mượn:");

        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Đến");

        txtngaymuon1.setEditable(false);
        txtngaymuon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaymuon1ActionPerformed(evt);
            }
        });

        txtngaytra1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtngaytra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtngaytra1MouseClicked(evt);
            }
        });
        txtngaytra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaytra1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtngaymuon1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4))
                    .addComponent(namekh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(txtthethanhvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(txtngaytra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtthethanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtngaytra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namekh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtngaymuon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel11)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Tiền khách đưa: ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 71, -1, -1));

        tienkhachdua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tienkhachduaActionPerformed(evt);
            }
        });
        jPanel2.add(tienkhachdua, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 68, 91, -1));

        jLabel13.setText("Tiền thừa:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 114, 86, -1));

        tienthua.setEditable(false);
        tienthua.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(tienthua, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 108, 91, -1));

        tongtien.setEditable(false);
        tongtien.setBackground(new java.awt.Color(204, 204, 204));
        tongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tongtienActionPerformed(evt);
            }
        });
        jPanel2.add(tongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 28, 91, -1));

        jLabel8.setText("Tổng giá:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 31, 61, -1));

        bang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã chi tiết", "Mã hóa đơn", "Mã video", "Tên video", "Giá", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bang1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bang1);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 51));
        jLabel10.setText("Hóa đơn số:");

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setText("Hóa đơn mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nhanvien.setForeground(new java.awt.Color(0, 102, 51));

        jButton4.setBackground(new java.awt.Color(51, 204, 255));
        jButton4.setText("Thanh toán");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 204, 255));
        jButton3.setText("Xuất hóa đơn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        trangthai.setText("Trạng thái!");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(229, 229, 229)
                        .addComponent(trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(42, 42, 42)
                                .addComponent(jButton3)
                                .addGap(156, 156, 156))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(341, 341, 341)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(77, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhanvien)
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(jButton3)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(trangthai))
                .addGap(87, 87, 87))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel14))
                    .addGap(12, 12, 12)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)))
                    .addContainerGap(363, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtngaymuon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaymuon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaymuon1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String idv = idvideo.getText();
        String namev = namevideo.getText();
        String p = price.getText();
        String q = quantity.getText();
        String tk = tonkho.getText();
        //int


        
        if (p.isEmpty() || q.isEmpty() || namev.isEmpty()| idv.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lỗi: Vui lòng nhập đầy đủ thông tin!", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }  else if (Integer.parseInt(q) > Integer.parseInt(tk)){
            JOptionPane.showMessageDialog(null, "Lỗi: Không đủ số lượng!", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else {
            int quantityValue = Integer.parseInt(q);
            int tonkhoValue = Integer.parseInt(tk);
            tonkhoValue = tonkhoValue - quantityValue;
            tonkho.setText(String.valueOf(tonkhoValue));
            int qint = Integer.parseInt(q);
            DBAccess acc = new DBAccess();
            ResultSet rs2 = acc.Query("insert into orderdetail(id_order,id_video,name_video,price_video, quantity_video) values ('" + jTextField1.getText() + "','" + idv + "','" + namev + "','" + p + "','" + q + "');");
            ResultSet rs = acc.Query("update video set video.quantity = video.quantity -" + qint +" where id_video = "+idv);
            Loaddata();

            ////Tính tổng tiền
//            int rowCount = bang1.getRowCount();
//            int totalPrice = 0;
//            for (int i = 0; i < rowCount; i++) {
//                int price = Integer.parseInt(bang1.getValueAt(i, 4).toString()) * Integer.parseInt(bang1.getValueAt(i, 5).toString());;
//                totalPrice += price;
//            }
            int totalPrice= getPriceBorrowDate();
            ResultSet rs3 = acc.Query("UPDATE orders SET total_price = " + totalPrice + " WHERE id_order =" + jTextField1.getText() + ";");
            
            tongtien.setText(String.valueOf(totalPrice));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ttv = txtthethanhvien.getText();
        String nm = txtngaymuon1.getText();
        String nt = txtngaytra1.getSelectedItem().toString();
        String tienthua1 = tienthua.getText();
        if (ttv.isEmpty() || nm.isEmpty() || nt.isEmpty() || tienthua1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lỗi: Vui lòng nhập đầy đủ thông tin!", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            In(bang1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void namekhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namekhActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namekhActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String ttv = txtthethanhvien.getText();
        String nm = txtngaymuon1.getText();
        String nt = txtngaytra1.getSelectedItem().toString();
        String tienthua1 = tienthua.getText();
//        String nv = nhanvien.getText();
        
 
        if (ttv.isEmpty() || nm.isEmpty() || nt.isEmpty() || tienthua1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lỗi: Vui lòng nhập đầy đủ thông tin!", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            DBAccess acc = new DBAccess();
            ResultSet test = acc.Query("SELECT id_order FROM orders WHERE id_order = " + jTextField1.getText() + ";");

            try {
                if (test.next()) {
                    // nếu đã có hóa đơn thì cập nhật lại
                    int id_order = test.getInt("id_order");
                    acc.Update("UPDATE orders SET membership_card = '" + ttv + "', borrow_date = '" + nm + "', return_date = '" + nt + "', id_admin = "+SharedData.adminID + " WHERE id_order = " + id_order + ";");
                    System.out.println("Updated id_order: " + id_order);
                    // Tính tổng tiền
                    String tt = tongtien.getText();
                    ResultSet rs3 = acc.Query("UPDATE orders SET total_price = " + tt + " WHERE id_order =" + jTextField1.getText() + ";");
                    trangthai.setText("Thanh toán thành công!");

                } else {
                    try (ResultSet rs2 = acc.Query("INSERT INTO orders (membership_card, borrow_date, return_date, trang_thai, id_admin) OUTPUT INSERTED.id_order VALUES ('" + ttv + "','" + nm + "','" + nt + "','chua tra',"+ SharedData.adminID +");")) {
                        if (rs2.next()) {
                            String tt = tongtien.getText();
                            ResultSet rs3 = acc.Query("UPDATE orders SET total_price = " + tt + " WHERE id_order =" + jTextField1.getText() + ";");
                            trangthai.setText("Thanh toán thành công!");
                        } else {
                            System.out.println("No rows returned after insertion.");
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Id = jTextField1.getText();
        int ida = Integer.parseInt(Id) + 1;
        try {
                // TODO add your handling code here:
                this.dispose();
                
                // Tạo một instance mới của form và hiển thị nó
                hoadon hd = new hoadon();
                hd.setVisible(true);
                hd.setTextField1Value(String.valueOf(ida));
            } catch (SQLException ex) {
                Logger.getLogger(hoadon.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tienkhachduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tienkhachduaActionPerformed
        // TODO add your handling code here:
        String tkd = tienkhachdua.getText();
        String tt = tongtien.getText();
        int a = Integer.parseInt(tkd);
        int b = Integer.parseInt(tt);
        int c = a - b;
        tienthua.setText(String.valueOf(c));
        
    }//GEN-LAST:event_tienkhachduaActionPerformed

    private void tongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tongtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tongtienActionPerformed

    private void bang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bang1MouseClicked
        // TODO add your handling code here:
        int row = bang1.getSelectedRow();
//        String machitiet = bang1.getValueAt(row, 0).toString();
////        String mahoadon = bang1.getValueAt(row, 1).toString();
////        String mavideo = bang1.getValueAt(row, 2).toString();
////        String tenvideo = bang1.getValueAt(row, 3).toString();
////        String gia = bang1.getValueAt(row, 4).toString();
////        String soluong = bang1.getValueAt(row, 4).toString();
//        
//        xoa.setText(machitiet);

        String machitiet = bang1.getValueAt(row, 2).toString();
        String soluongmuon = bang1.getValueAt(row, 5).toString();
        String sql = "Select id_video, name_video, category_video, price, quantity from video where id_video = '"+machitiet+"'";
        DBAccess ac= new DBAccess();
        ResultSet a = ac.Query(sql);
            try {
                while (a.next()){
                    idvideo.setText(a.getString("id_video"));
                    namevideo.setText(a.getString("name_video"));
                    price.setText(a.getString("price"));
                    category.setText(a.getString("category_video"));
                    tonkho.setText(a.getString("quantity"));
                    quantity.setText(soluongmuon);
                }   } catch (SQLException ex) {
                Logger.getLogger(hoadon.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_bang1MouseClicked

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed

          int row = bang1.getSelectedRow();
          if (row != -1) {
          String machitiet = bang1.getValueAt(row, 0).toString();
          String idv = bang1.getValueAt(row, 2).toString();
          String soluong = bang1.getValueAt(row, 5).toString();
          int soluongint = Integer.parseInt(soluong);
          int idvint = Integer.parseInt(idv);
          DBAccess acc = new DBAccess();
          ResultSet rs2 = acc.Query("update video set video.quantity = video.quantity +" + soluongint +" where id_video = "+idv);
          ResultSet rs = acc.Query("delete from orderdetail where id_orderdetail = "+machitiet);
          tongtien.setText(String.valueOf(getPriceBorrowDate()));
          Loaddata();
          } else {
           JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
          }
          
          ////load
                  String sql = "Select name_video, category_video, price, quantity from video where id_video = '"+idvideo.getText()+"'";
        DBAccess ac= new DBAccess();
        ResultSet a = ac.Query(sql);
            try {
                while (a.next()){
                    namevideo.setText(a.getString("name_video"));
                    price.setText(a.getString("price"));
                    category.setText(a.getString("category_video"));
                    tonkho.setText(a.getString("quantity"));
                }   } catch (SQLException ex) {
                Logger.getLogger(hoadon.class.getName()).log(Level.SEVERE, null, ex);
            }
          
    }//GEN-LAST:event_xoaActionPerformed

    private void txtthethanhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtthethanhvienActionPerformed
        // TODO add your handling code here:
        String sql = "Select * from customer where membership_card = '" + txtthethanhvien.getText() + "'";
        DBAccess ac = new DBAccess();
        ResultSet a = ac.Query(sql);
        try {
            while (a.next()) {
                namekh.setText(a.getString("name_khachhang"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtthethanhvienActionPerformed

    private void idvideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idvideoActionPerformed
        // TODO add your handling code here:
        String sql = "Select name_video, category_video, price, quantity from video where id_video = '"+idvideo.getText()+"'";
        DBAccess ac= new DBAccess();
        ResultSet a = ac.Query(sql);
            try {
                while (a.next()){
                    namevideo.setText(a.getString("name_video"));
                    price.setText(a.getString("price"));
                    category.setText(a.getString("category_video"));
                    tonkho.setText(a.getString("quantity"));
                }   } catch (SQLException ex) {
                Logger.getLogger(hoadon.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_idvideoActionPerformed

    private void txtngaytra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaytra1ActionPerformed
//        int rowCount =bang1.getRowCount();
//        if(rowCount > 0 ){
//            int totalPrice = 0;
//            for (int i = 0; i < rowCount; i++) {
//                int price = Integer.parseInt(bang1.getValueAt(i, 4).toString()) * Integer.parseInt(bang1.getValueAt(i, 5).toString());
//                totalPrice += price;
//            }
//
//            int ngayTra = txtngaytra1.getSelectedIndex();
//        if(ngayTra==0 ){
//                tongtien.setText(String.valueOf(totalPrice));
//            }else if(ngayTra == 1){
//                tongtien.setText(String.valueOf(((totalPrice*25)/100)+totalPrice));
//            }else if(ngayTra ==2){
//                tongtien.setText(String.valueOf(((totalPrice*50)/100)+totalPrice));
//            }
//        }
    }//GEN-LAST:event_txtngaytra1ActionPerformed

    private void txtngaytra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtngaytra1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaytra1MouseClicked
    public void In(JTable jTable1) {

        JFileChooser chooser = new JFileChooser();
        int result = chooser.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();

            try (FileWriter out = new FileWriter(file + ".docx");
                 BufferedWriter b_write = new BufferedWriter(out)) {

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                Date date = new Date();

                // Header
                b_write.write("        HÓA ĐƠN \n");
                b_write.write("Ngày:" + date.toString() + "\n");
                b_write.write("Nhân viên phụ trách:" + nhanvien.getText() + "\n");
                b_write.write("Thẻ thành viên số:" + txtthethanhvien.getText() + "\n");
                b_write.write("Tên khách hàng:" + namekh.getText() + "\n");
                b_write.write("-------------------------------------------------------\n");

                // Rental dates
                b_write.write("Ngày mượn:" + txtngaymuon1.getText() + "\n");
                b_write.write("Ngày trả:" + txtngaytra1.getSelectedItem().toString()+ "\n");

                // Table header
                for (int j = 3; j < jTable1.getColumnCount(); j++) {
                    b_write.write(String.format("%-20s", model.getColumnName(j)));
                }
                b_write.write("\n");

// Table data excluding the first column
                for (int j = 0; j < jTable1.getRowCount(); j++) {
                    for (int k = 3; k < jTable1.getColumnCount(); k++) {
                        b_write.write(String.format("%-20s", model.getValueAt(j, k)));
                    }
                    b_write.write("\n");
                }

                // Footer
                b_write.write("-------------------------------------------------------\n");
                b_write.write("Tổng tiền:                " + tongtien.getText() + "vnd\n");
                b_write.write("Tiền khách đưa:           " + tienkhachdua.getText() + "vnd\n");

                int tienthua = Integer.parseInt(tienkhachdua.getText()) - Integer.parseInt(tongtien.getText());
                b_write.write("Tiền thối lại cho khách:  " + tienthua + "vnd\n");

                JOptionPane.showMessageDialog(null, "Lưu file thành công !");
            } catch (Exception e2) {
                JOptionPane.showMessageDialog(null, "Lưu file thất bại !");
            }
        }
    }
    private void Loaddata(){
        String sql = "Select * from orderdetail where id_order ='" + jTextField1.getText() +"';";
        DBAccess acc= new DBAccess();
        try {
        ResultSet rs = acc.Query(sql);    
        String [] arr = {"Mã chi tiết","Mã hóa đơn","Mã video","Tên video","giá", "số lượng"};
        DefaultTableModel model = new DefaultTableModel(arr,0);        
            while (rs.next()){
                Vector vec = new Vector();
                vec.add(rs.getString("id_orderdetail"));
                vec.add(rs.getString("id_order"));
                vec.add(rs.getString("id_video"));
                vec.add(rs.getString("name_video"));
                vec.add(rs.getString("price_video"));
                vec.add(rs.getString("quantity_video"));
                model.addRow(vec);
            }
            bang1.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(hoadon.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bang1;
    private javax.swing.JTextField category;
    private javax.swing.JTextField idvideo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField namekh;
    private javax.swing.JTextField namevideo;
    private javax.swing.JLabel nhanvien;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField tienkhachdua;
    private javax.swing.JTextField tienthua;
    private javax.swing.JTextField tongtien;
    private javax.swing.JTextField tonkho;
    private javax.swing.JLabel trangthai;
    private javax.swing.JTextField txtngaymuon1;
    private javax.swing.JComboBox<String> txtngaytra1;
    private javax.swing.JTextField txtthethanhvien;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
